(defpackage :k02
    (:use :cl)
    (:export #:question-1 #:question-2 #:question-3 #:question-4))

(in-package :k02)

(load (merge-pathnames "shared/golem.lisp"))

(defun question-1 () 
    (let ((seisuu 3)
        (jissuu 2.6)
        (moji #\A))
        (format t "変数seisuuの値は~a~%" seisuu)
        (format t "変数jissuuの値は~a~%" jissuu)
        (format t "変数mojiの値は~a~%" moji)))

(defun question-2 ()
    (print "一つ目の整数は？")
    (finish-output)
    (let ((number-1 (parse-integer (read-line) :junk-allowed t)))
        (print "二つ目の整数は？")
        (finish-output)
        (let ((number-2 (parse-integer (read-line) :junk-allowed t)))
            (format t "~a÷~a=~a...~a" number-1 number-2 (/ number-1 number-2) (mod number-1 number-2)))))

(defun question-3 ()
    (print "一つ目の商品の値段は？")
    (finish-output)
    (let ((price-a (coerce (parse-integer (read-line) :junk-allowed t) 'single-float)))
        (print "個数は？")
        (finish-output)
        (let ((amount-a (coerce (parse-integer (read-line) :junk-allowed t) 'single-float)))
            (print "二つ目の商品の値段は？")
            (finish-output)
            (let ((price-b (coerce (parse-integer (read-line) :junk-allowed t) 'single-float)))
                (print "個数は？")
                (finish-output)
                (let* ((amount-b (coerce (parse-integer (read-line) :junk-allowed t) 'single-float))
                    (total (* 1.1 (+ (* price-a amount-a) (* price-b amount-b)))))
                    (format t "お支払いは税込み￥~a~%" total))))))

(defun question-4 ()
    (let ((golem (golem:make-golem :hp 300 :defense 80 :attack 50)))
    (format t "ゴーレム　（HP：~a　防御力：~a）~%"
        (golem:golem-hp golem)
        (golem:golem-defense golem))
    (format t "HP：~a~%" (golem:golem-hp golem))
    (print "今回の攻撃の値を入力してください＞")
    (finish-output)
    (let* ((damage (parse-integer (read-line) :junk-allowed t))
        (final-damage (if (> (- damage (golem:golem-defense golem)) 0) (- damage (golem:golem-defense golem)) 0)))
    (format t "ダメージは~aです。~%" final-damage)
    (decf (golem:golem-hp golem) final-damage)
    (format t "残りのHPは~aです。~%" (golem:golem-hp golem)))))