name:                HelloWorld
version:             0.1.0.0
github:              "githubuser/HelloWorld"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/HelloWorld#readme>

dependencies:
- base >= 4.7 && < 5
- random >= 1.2.0
- text >= 1.2.4.1
- containers >= 0.6.2.1
- HUnit >= 1.6.2.0

library:
  source-dirs: src

executables:
  HelloWorld-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HelloWorld

tests:
  HelloWorld-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HelloWorld
